Only request country information on kyc-enabled communities
cambiatus/frontend pull request #368
Opened 2020-09-22 18:15 UTC by RodrigoLeiteF

## What issue does this PR close
Closes N/A

## Changes Proposed ( a list of new changes introduced by this PR)
Limits registration form to only request country information if invited community is KYC-enabled.

## How to test ( a list of instructions on how to test this PR)
1. Open the browser network console
2. Go to a community with no kyc enabled
3. Look at the requests

2020-09-22 21:33 UTC, lucca65 requested changes

2020-09-22 21:33 UTC, lucca65 commented on src/elm/Page/Register.elm
> +dummyCountry =
I don't think this is a good idea, we can know from the invitation what is the community, and thus know if it have KYC enabled, we can do better!

2020-09-24 14:37 UTC, amiskov approved these changes

2020-09-24 18:09 UTC, lucca65 approved these changes

2020-09-24 18:09 UTC, merged