Fix/invalid character message
cambiatus/frontend pull request #375
Opened 2020-09-29 21:33 UTC by RodrigoLeiteF

## What issue does this PR close
Closes #373 

## Changes Proposed ( a list of new changes introduced by this PR)
1. Changes the invalid character message

## How to test ( a list of instructions on how to test this PR)
1. Go to the register form
2. Enter an invalid account name
3. Click continue

2020-09-30 09:18 UTC, amiskov requested changes
I agree with the changing of the message. I don't think that we need to show all the wrong characters to the user in `{{invalidChar}}`, it's just unnecessary.

Here's only one thing to improve. The message should have a little more margin from the right to not overlap the counter:
![image](https://user-images.githubusercontent.com/140053/94666852-ace84880-0316-11eb-8bc8-beedd3183737.png)

2020-09-30 09:21 UTC, amiskov commented
@RodrigoLeiteF Just for the note, I changed the base branch for this PR to `kyc` (initially it was `master`).

2020-09-30 17:04 UTC, lucca65 approved these changes

2020-10-01 14:33 UTC, amiskov approved these changes
👍

2020-10-01 15:31 UTC, merged