Feature/msig
cambiatus/frontend pull request #649
Opened 2021-10-08 15:56 UTC by NeoVier

## What issue does this PR close
Closes #639 

## Changes Proposed ( a list of new changes introduced by this PR)
- Adicionar abilidade de configurar multisig, e usá-la pra propor, votar e executar transações EOS

## How to test ( a list of instructions on how to test this PR)
Por enquanto, tudo está hardcoded no módulo `Page.Community.Settings.Multisig`. Se quiser testar, mude os valores nesse arquivo para usar suas contas.

- Acesse `/community/settings/multisig`
- Configure as contas que receberão permissão para propor, votar e executar transações
- Proponha uma transação
- Vote na transação até ela estar aprovada (2 votos)
- Execute a transação

2022-03-25 12:38 UTC, lucca65 commented
Bro, I think we should update this PR, maybe there is still time so the merge won't be too crazy. We are getting near it 👀

2022-05-13 13:36 UTC, lucca65 commented
ping @NeoVier, we should update this with master, it will get harder to do so as time progresses

2022-05-13 14:01 UTC, NeoVier commented
![image](https://user-images.githubusercontent.com/39280468/168300277-24f809f8-9941-4132-8e3c-8c1db2b1d1d8.png)


🚴

2022-05-13 14:05 UTC, lucca65 commented
damn... well we can simply drop this and make it again in the future.. by the looks we still got plenty to do before implementing this feature

2022-05-13 14:06 UTC, NeoVier commented
Actually the merge conflicts don't seem too bad to be honest

2022-09-07 02:25 UTC, NeoVier commented
@lucca65 I think we're probably not going to work on this in the foreseeable future (and haven't worked on it in a while). Should we close this PR?

2022-09-07 21:47 UTC, lucca65 requested changes
Acho que o melhor a se fazer é alterar o PR para ser um PR que só coloca lib no projeto. Assim preservamos a excelente documentação e módulo que você fez, que facilita nosso trabalho mais tarde!

2022-09-09 14:06 UTC, NeoVier commented
Então bro, eu to pra lançar uma ferramenta que faz 90% do que esse PR faz (pega um ou mais contratos, e gera todo o código elm necessário pra interagir com eles). Se formos usar ela, não sei se vale muito a pena manter o que fizemos nesse PR - a maior parte do código desse PR teria que ser refeito.

Talvez podemos manter a branch pra manter a documentação, mas fechar o PR, o que acha?

Ainda não tá publicado no npm ou nos pacotes elm (mas já dá pra ir usando, tem [um exemplo na pasta `examples`](https://github.com/NeoVier/elm-eos/blob/main/examples/memberFetching/src/Main.elm) que faz o mesmo que o [script pra pegar o saldo dos usuários](https://github.com/cambiatus/eosQuery)), pq falta arrumar algumas coisas, mas a ferramenta é essa aqui: https://github.com/NeoVier/elm-eos. A ideia é ser bem parecida com dillonkearns/elm-graphql

2022-09-12 17:06 UTC, lucca65 commented
Nossa bro que show isso! beleza faz todo sentido então! parabéns pela visão, incrível ter algo desse tipo. Inclusive, uma recomendação pessoal que dou é de falar com o Luiz para ir atrás de um grant pra isso. É bem oq a pomelo e o eos foundation querem!

2022-09-13 18:17 UTC, NeoVier commented
Vou fechar o PR e manter a branch por enquanto. Vou fazer um port das funcionalidades de multisig que fizemos nesse PR como um exemplo no repo do `elm-eos`, e quando terminar, deleto a branch. Assim, se formos implementar multisig na Cambiatus, podemos seguir o exemplo de lá

2022-09-13 18:17 UTC, closed without merging