Enhancement/shop facelift
cambiatus/frontend pull request #690
Opened 2022-02-18 02:26 UTC by NeoVier

## What issue does this PR close
Closes #657 

## Changes Proposed ( a list of new changes introduced by this PR)
- Add the tailwind `line-clamp` plugin. Useful for when user-entered text might break the layout if it's too long, so we can limit the number of lines to display.
- Improve accessibility for some components:
  - Profile summary
  - Rich text editor
  - File uploader
  - Text fields with currency
  - LoggedIn footer
- Rewrite most of the view code for shop-related pages (even though their behavior/content shouldn't change much, if at all):
  - Shop listing (`/shop`)
  - Product view (`/shop/:id`)
  - Product editor (`/shop/new/sell` and `/shop/:id/edit`)
  - Transfer view (`/transfer/:id`)

## How to test ( a list of instructions on how to test this PR)

Go through the pages and see if they match the design. Also test if they work as intended

## Still TODO

- Confirm if the "Contact the seller" component should still be shown if the user is the owner of the sale (https://www.figma.com/file/rT5DMvPAtvbHSxNBwQENDM?node-id=1964:11937#154371495)
- We need the auth and contracts PRs in order to test this fully (we need to be authenticated to create/edit sales, and to buy stuff)

2022-02-24 14:26 UTC, lucca65 requested changes
Just found one thing, that happens when resizing the window. It also happened on the iPad (where its somewhat common to resize stuff

https://user-images.githubusercontent.com/1082127/155542612-59cea033-bb33-42be-ba17-19b1438dd6a6.mov

2022-02-24 15:32 UTC, NeoVier commented
Oh safari 😩 I'll look into it!

2022-02-24 23:40 UTC, lucca65 approved these changes
wow, actually looks way better

2022-02-25 18:16 UTC, juramos-2020 commented
OI @NeoVier 

**Segue teste realizado na versão Desktop**:

- Ao finalizar uma compra, não apareceu a [tela de sucesso](https://www.figma.com/file/rT5DMvPAtvbHSxNBwQENDM/New-shop---v1?node-id=1986%3A14344) ⚠

- Ao efetuar uma transferência a tela de sucesso apareceu conforme o esperado ✔

- Na tela de sucesso está faltando as informações de contato de quem está recebendo a transferência [conforme design](https://www.figma.com/file/rT5DMvPAtvbHSxNBwQENDM/New-shop---v1?node-id=1986%3A14344). ⚠


E só um detalhe, você poderia adicionar um espaçamento de 4px entre o titulo da oferta e o nome de quem a criou?

![image](https://user-images.githubusercontent.com/67649886/155764849-57d5aaa5-017b-4282-86ae-02c2991278d9.png)

2022-02-25 18:58 UTC, juramos-2020 commented
**Para a versão mobile seguem as mesmas observações que fiz para a versão desktop** e estou 
adicionando mais essas: 👇

- Os botão de **"criar nova"** e **"ver as minhas"** devem ser do mesmo tamanho e alinhados [conforme design](https://www.figma.com/file/rT5DMvPAtvbHSxNBwQENDM/New-shop---v1?node-id=1964%3A11584)

- Os emojis que aparecem na tela de sucesso podem ficar um pouco menor. Qual tamanho vc está usando para cada um deles? Pode tentar 32x32px ou 24x24px?

- Fiz uma alteração [nessa tela do design](https://www.figma.com/file/rT5DMvPAtvbHSxNBwQENDM/New-shop---v1?node-id=1964%3A12439) para adicionarmos essas descrições no campo de "nome do produto" e "descreva o produto", pois temos esse padrão em outros lugares do app. O que vc acha? faz sentido?

2022-02-26 17:51 UTC, lucca65 commented
Pessoal essa testa (espaço grande entre a barra de cima e o conteúdo) que fica é intencional?

<img width="1205" alt="Captura de Tela 2022-02-26 às 14 50 24" src="https://user-images.githubusercontent.com/1082127/155853792-43d13348-ebd3-442f-bfea-8a349d456659.png">

2022-02-26 17:56 UTC, NeoVier commented
Mais um bug do safari com CSS 😩 Parece que só acontece com telas grandes e só no safari. Vou investigar!

2022-02-26 18:39 UTC, juramos-2020 commented
Oi @NeoVier 

O campo do comentário, na página do produto, tá com essa quebra nas opções de rich text
![Screenshot_2022-02-26-15-32-36-344_com android chrome](https://user-images.githubusercontent.com/67649886/155855023-7529c201-bd1a-4e5b-b5ac-8eee22bc4831.jpg)


E ao finalizar uma compra a tela de sucesso continua não aparecendo.

2022-02-26 19:15 UTC, NeoVier commented
> O campo do comentário, na página do produto, tá com essa quebra nas opções de rich text

Isso depende do tamanho da tela, se os ícones não cabem em uma linha, eles vão pra próxima linha 🤷. Diminui o espaçamento entre os grupos de ícones, assim talvez acomode mais tamanhos de tela, mas não tem como fazer muito mais do que isso

> E ao finalizar uma compra a tela de sucesso continua não aparecendo.

Olhei para a linha de código que precisava mudar, fui fazer outra coisa e esqueci de mudar 🤦. Porém, fica difícil fazer isso com a nossa API atual também (ao mandar a transação para a blockchain, não recebemos o ID da transferência que representa a compra, apenas o ID da transação EOS). E como não conseguimos saber a diferença entre uma transferência normal e uma transferência do shop, não conseguimos saber com certeza qual transação representa essa compra. Vamos ter que deixar essa parte para quando atualizarmos a API também 😬

2022-02-26 19:17 UTC, NeoVier commented
@lucca65 bons pontos para considerar no refactoring da API do shop ☝️

TLDR:
- Receber o ID da transferência quando ela for feita (no momento, recebemos só o ID da transação EOS) (assim podemos redirecionar para a página de transferência)
- Diferenciar entre transferências normais e transferências/compras do shop (assim podemos mostrar uma tela de sucesso, que mostra dados do vendedor/comprador, da transferência e do produto)

2022-02-26 19:25 UTC, lucca65 commented
> Receber o ID da transferência quando ela for feita (no momento, recebemos só o ID da transação EOS) (assim podemos redirecionar para a página de transferência)

bro, não é possível receber o id da transferencia (do GraphQL) só a da transação (do eos) não tem como contornar isso, nem com a API nova. 

> Diferenciar entre transferências normais e transferências/compras do shop (assim podemos mostrar uma tela de sucesso, que mostra dados do vendedor/comprador, da transferência e do produto)

há diferença! você pode consultar com as notificações (objeto `notificationHistory`), que tem detalhes da venda. Há uma tela que já conversamos diversas vezes com o @heltonlr que não dá pra fazer, não sei se é essa a tela que a @juramos-2020 menciona. Até hoje mostramos a tela de transferencia. Tela de pedido com status de pagamento (essa sim dá pra fazer) só depois do refactor!!

2022-02-26 20:02 UTC, NeoVier commented
> você pode consultar com as notificações (objeto notificationHistory), que tem detalhes da venda

Verdade, mas teríamos que mudar os dados que guardamos no front agora em relação a notificações (não guardamos o campo `payload`) (ou fazer uma query a mais sempre que o usuário entrar na tela de ver transferência), e teríamos que procurar em todas as notificações, pra ver se achamos uma que corresponde à venda. Acho que essa mudança nas notificações seria uma grande mudança, e não é tão relacionada a esse PR, então sugiro revermos isso (se quiserem) em #685, ou até em outra issue

A "tela de sucesso" é a tela de transferência mesmo, a única diferença é que teria uma seção com dados sobre o vendedor do produto (a parte de "Contact the seller"):

<img width="574" alt="image" src="https://user-images.githubusercontent.com/39280468/155856955-25bc6018-b205-4c07-98d0-96e6f41549be.png">


https://www.figma.com/file/rT5DMvPAtvbHSxNBwQENDM/New-shop---v1?node-id=1986%3A14344

2022-02-26 20:15 UTC, NeoVier commented
+1 pra esperar a estrutura de pedido

2022-02-26 23:26 UTC, juramos-2020 commented
Ah tá tranquilo então, vamos aguardar para fazer isso depois como o Lucca sugeriu 😉👍

2022-03-01 13:53 UTC, juramos-2020 commented
OI @NeoVier tudo finalizado com os testes. 😉

Essa questão das "informações de contato na tela de sucesso" e da "tela de sucesso" ao finalizar uma compra vamos resolver depois de resolvermos a isso[ 148](https://github.com/cambiatus/backend/issues/148 )

2022-03-02 01:38 UTC, NeoVier commented
@lucca65 esse PR tá aprovado ou ainda falta alguma mudança?

2022-03-02 11:20 UTC, merged