Enhancement/how to earn
cambiatus/frontend pull request #716
Opened 2022-03-29 23:15 UTC by NeoVier

## What issue does this PR close
Closes #670 

## Changes Proposed ( a list of new changes introduced by this PR)
- [ ] Change the objectives page
- [ ] New claim designs 
- [x] Create an "about the community" page 

## How to test ( a list of instructions on how to test this PR)
Go through the app and see if the screens look like the designs and keep their functionality

2022-04-16 00:58 UTC, lucca65 requested changes
Gostei bastante do resultado final! Tá bem bonito, inclusive alguns detalhes como a animação na hora de abrir um objetivo! ficou incrível!

queria pedir umas alterações, só detalhes como de praxe:

1. Pode colocar a animação ao fechar objetivo também? Acho que ia ficar bem bonito 😁 
2. A URL de compartilhamento de ação poderia ser mais semântica: `/objectives/{objetive_id}/action/{action_id}`
3. Fiquei sentindo falta de um botão que levasse da tela da comunidade para a tela de objetivos, como o que temos agora. Talvez dá pra colocar um link nos cards? não queria propor mudanças no layout nessa altura do campeonato, mas se for tranquilo de colocar, acho que seria legal ter uma forma de ir pros objetivos quando estamos explorando a comunidade.
4. Quando uma comunidade não possui apoiadores ou noticias o card de descrição fica bem pequeno e centralizado na tela, será que daria pra deixá-lo maior? o espaço vazio ali precisando de scroll pra ver os números não fica mt legal

Algumas outras coisas que achei legais na implementação:
- a animação ao abrir objetivo ficou show
- o mosaico de ações com imagem fica bem legal, gostei da densidade 
- o modal de claim num dispositivo móvel abre com o scroll lá em baixo, direto nos botões, gostei muito

2022-04-19 01:18 UTC, NeoVier commented
+1, fiquei muito feliz com o resultado final e gostei muito (além de aprender muita coisa e usar ferramentas novas) de desenvolver essas telas, principalmente a de objetivos. Diria que é a interface mais complexa do nosso app até agora:
- O grid, com masonry layout, é difícil de acertar, e acho que ficou perfeito, com direito a animações! Além disso, é 100% reutilizável, feito com um webcomponent
- O carrossel ficou com uma boa acessibilidade, o que é geralmente bem difícil de conseguir, e ele usa algumas coisas legais como `scroll-snap` e `IntersectionObserver`, que eu sempre tinha curiosidade de usar 😅 
- Conseguimos acomodar esses dois componentes sem mexer na DOM! Ambos têm a mesma estrutura, só diferem em algumas classes de CSS e algumas chamadas de JS

---

> Fiquei sentindo falta de um botão que levasse da tela da comunidade para a tela de objetivos, como o que temos agora. 

Experimentei colocar um card igual ao que tem na tela de objetivos que leva para a página sobre a comunidade, mas preferi deixar no card com a descrição da comunidade


> Quando uma comunidade não possui apoiadores ou noticias o card de descrição fica bem pequeno e centralizado na tela, será que daria pra deixá-lo maior?

Tinha deixado desse tamanho pra deixar alinhado com os cards de "Nossos números", mas concordo que ficou pequeno. Aumentei pra ocupar o tamanho de 2 desses cards (mas centralizado na tela), acho que ficou melhor! Acredito que não fica legal deixar do tamanho inteiro da tela

2022-04-19 01:51 UTC, lucca65 submitted a review, later dismissed

2022-04-19 01:52 UTC, lucca65 commented
Gostei! Ficou show!!

2022-04-19 22:42 UTC, juramos-2020 commented
Oi @NeoVier 

primeiramente ficou incrível, parabéns! Foi lindo de ver o carinho que você depositou construindo tudo isso e adicionando aquele efeito, achei lindo demais 💚

Seguem alguns pequenos ajustes:
- Na página da comunidade, [atualizar os ícones com seus respectivos nomes conforme design](https://www.figma.com/file/l2HhpioJFpVSUW6E5ZjBn9/Acessibilidade?node-id=1054%3A48148)
- Na página de "How to earn", no último card, centralizar o texto "Visite a página da comunidade para saber mais sobre" e adicionar um espaçamento de 08 px entre ele e o cachorrinho.
- Na versão mobile, em "How to earn", dentro de um objetivo sem ações, o texto do empty state deve estar centralizado também.
- No card das ações, adicionar o elemento de "Members claimed this action"  [conforme design](https://www.figma.com/file/l2HhpioJFpVSUW6E5ZjBn9/Acessibilidade?node-id=793%3A39629).
- No card das ações os textos relacionados a **prova fotográfica**, deve ser alinhado a esquerda [conforme design](https://www.figma.com/file/l2HhpioJFpVSUW6E5ZjBn9/Acessibilidade?node-id=783%3A17909)

2022-04-20 04:22 UTC, NeoVier commented
Feito @juramos-2020!

> No card das ações, adicionar o elemento de "Members claimed this action"

Pensei que tínhamos conversado de deixar esse elemento só no modal de claim (quando o usuário realmente clica em "Reivindicar"). Coloquei pra ver como ficava para poder ter a opinião de vocês... eu pessoalmente gosto do card limpo, bem simples, mas por outro lado, pode ser interessante (mas não essencial) ter essa informação antes de reivindicar a ação.

Enfim, o que acham @lucca65 @juramos-2020 @rafachadud, deixamos esse elemento de contagem de claims da ação no card da ação também, ou só no modal de claim?

2022-04-20 10:21 UTC, juramos-2020 commented
Oi @NeoVier, eu lembro bem vagamente da conversa e se eu não me engano acho que foi o @lucca65 que tinha sugerido essa melhoria. Sinceramente não tenho nenhum argumento que defenda a permanência ou a ausência dessa informação no card. Como você disse, é algo interessante mas realmente não é essencial. Bom... vou deixar a critério de vcs @lucca65 e @rafachadud 😉

2022-04-20 10:40 UTC, juramos-2020 commented
@NeoVier 

ao clicar em "Ganhe Buss" no card do perfil da comunidade e abrir a página de "How to aern", o scrol vai direto para o card do cachorrinho que fica no final da página. 

E ao usar o scrol lateral para fazer a rolagem dos cards, vi que está acontecendo tipo uma falha. Mas não sei se isso é um bud do meu celular...

https://user-images.githubusercontent.com/67649886/164212936-74ce451b-6f32-4183-adfa-39f89a7ffaa4.mp4

2022-04-20 12:50 UTC, NeoVier commented
Não é bug no celular não, @juramos-2020 😅. É uma rara ocasião em que funciona no Safari, mas não nos outros browsers. Estou investigando pra resolver 🏃‍♂️

2022-04-20 17:13 UTC, juramos-2020 commented
Maravilha @NeoVier ficou show de bola  ✨😉✌🎉

2022-04-20 20:32 UTC, lucca65 commented
Pessoal, por mim fica dentro do modal!

2022-04-21 16:30 UTC, lucca65 approved these changes
Incrível! vou preparar a release draft

2022-04-21 18:08 UTC, merged