Feature/edit community contacts
cambiatus/frontend pull request #740
Opened 2022-04-29 14:09 UTC by NeoVier

## What issue does this PR close
Closes #713 

## Changes Proposed ( a list of new changes introduced by this PR)
- [x] Add card on the community settings page that points to the new page
- [x] Add the screen to add community contacts
  - [x] Create basic layout
  - [x] Layout form structure
  - [x] Create new fields on demand
  - [x] Remove fields on demand
  - [x] Integrate with existing contact types and functions
- [x] Show community contacts on the footer

To make things better with our current architecture, I created a new `Contact` module to organize the contact form and related types, functions and views. That means we now have `Contact` and `Profile.Contact`, where `Contact` is used for community contacts, and `Profile.Contact` is used for profile contacts. In order to not clutter this PR too much, I will leave the work of removing `Profile.Contact` in favor of `Contact` for another issue/PR

## How to test ( a list of instructions on how to test this PR)
- Log in to a community you're the admin of
- Before adding contacts, check that the footer looks right (it shouldn't have contacts yet)
- Go to the settings page
- Go to the community contacts page
- Interact with the form: add, edit and remove contacts to test it out
- Save the form
- Check the footer again to see if it looks right (now it should have contacts displayed there)
- Click on the link to use the community contacts. Check it when your community has a single contact option, and when it has more than one (a modal should be displayed, to allow you to choose which contact you want to use)
- Delete all contacts and make sure the footer doesn't show the contacts link again

2022-05-10 14:46 UTC, NeoVier commented
I adjusted the size of the form inputs. I'd say the idea is that the labels should be short and descriptive, and I think the small form input encourages that. On the other hand, it might be frustratingly small 😬

2022-05-10 14:46 UTC, NeoVier commented
Maybe @juramos-2020 can help us out here ☝️

2022-05-10 23:37 UTC, lucca65 approved these changes
Oh, forgot to approve the PR. @juramos-2020 I think we could have a minimum font size to make readability possible.

2022-05-12 15:10 UTC, juramos-2020 commented
@NeoVier quanto de largura vc está usando nesse board branco? Podemos usar 810px [conforme layout](https://www.figma.com/file/RSoh4DDEj0N1TVkQT0SxIn/Header-and-Footer?node-id=1365%3A2831)
Também acho que nessa primeira tela não precisa ter o botão de salvar pelo fato de ainda não ter nada para salvar.
![image](https://user-images.githubusercontent.com/67649886/168107587-613f149f-9902-4368-be85-eb7c327df21c.png)

2022-05-12 15:16 UTC, juramos-2020 commented
@NeoVier 

Teria como termos aqueles espaçamentos automáticos quando a gente preenche um campo de telefone? 
Não sei se to sabendo explicar direito... mas seria algo assim, ex: digito 11 do DDD e aí automaticamente se cria os "()" e o espaço em branco.
Você sabe como é? 🙈🙈😅

![image](https://user-images.githubusercontent.com/67649886/168108946-f79cab78-b291-4ec9-a41c-ca8fa50e3f93.png)

2022-05-12 15:23 UTC, juramos-2020 commented
⚠E agora estou tentando salvar o formulário com os campos preenchidos corretamente mas não está salvando. Está dando erro.

![image](https://user-images.githubusercontent.com/67649886/168110813-05a75e5f-49a9-44da-bf59-768b4918f94c.png)

2022-05-12 15:26 UTC, juramos-2020 commented
⚠ Quando eu adiciono uma opção nova de conta ela já abre com um alerta de erro:

![image](https://user-images.githubusercontent.com/67649886/168111455-1e87ba8d-06e0-4678-99cf-30adf5be7aec.png)

2022-05-12 17:38 UTC, juramos-2020 commented
OI @NeoVier 

> Podemos alterar se quiser, mas acredito que seria bom termos mais espaço para a label
Qual seria o tamanho máximo que vc acha que podemos ter para uma label? Podemos falar melhor sobre isso [aqui no figma](https://www.figma.com/file/RSoh4DDEj0N1TVkQT0SxIn/Header-and-Footer?node-id=1374%3A5206)? acho que fica melhor para eu entender e poder sugerir algo melhor.
Estamos tentando seguir um padrão de design nas telas, principalmente na versão desktop aonde temos um "problema bom" de muito espaço rsrsrs.

2022-05-13 13:41 UTC, lucca65 requested changes
@NeoVier O que acha da gente deixar o valor padrão da label como vazia mas com um placeholder? Se o usuário não colocar nada fica com o valor padrão. Hoje está vindo preenchido com texto direto. Acho que o placeholder faria mais sentido aqui

2022-05-13 20:56 UTC, juramos-2020 commented
@NeoVier

segue a [versão desk](https://www.figma.com/file/RSoh4DDEj0N1TVkQT0SxIn/Header-and-Footer?node-id=1374%3A5206) atualizada.

Sobre a fonte dos rótulos dos icones sugiro seguirmos com essas especificações:
Font: Nunito Sans
Size: 12px
Line height: 22px

Acabei de fazer o teste na versão mobile e funcionou tudo como o esperado 🎉
Esta faltando só o ajuste da fonte do label do ícone 😎

2022-05-15 01:48 UTC, lucca65 approved these changes
Incrível adorei essa funcionalidade 🏅

2022-05-15 01:56 UTC, merged