Fix/action modal text
cambiatus/frontend pull request #743
Opened 2022-05-02 20:20 UTC by NeoVier

## What issue does this PR close
Closes #741 

## Changes Proposed ( a list of new changes introduced by this PR)
- Remove rogue `truncate` class on action description
- Revisit logic behind modal sizing (`max-height` is now set on `modal-content` instead of `modal-body`)
- Make claim modal taller
- Put modal buttons on footer

## How to test ( a list of instructions on how to test this PR)
- Go to the "How to earn page" (`/community/objectives`)
- Open the modal for an action with a long description
- Check that you can read the entire description
- Check that the buttons to claim or cancel are always visible on the bottom of the modal
- If the action contents are big enough, the modal should now be able to grow taller (up to 95% of your screen height)

2022-05-02 20:21 UTC, NeoVier commented on src/elm/Page/Community/Objectives.elm
> +                            [ Markdown.view [] action.description
🤦

2022-05-02 20:30 UTC, lucca65 requested changes
It behaves weirdly on Safari Desktop

<img width="1251" alt="Captura de Tela 2022-05-02 às 17 30 04" src="https://user-images.githubusercontent.com/1082127/166322555-dabc7974-5964-402e-b200-9ec1d3f5e4cd.png">

2022-05-02 21:08 UTC, NeoVier commented
I think that's a bug on Safari and Firefox, as it works on Chrome. Because of that, I don't think we can have a reliable solution to always show 3 lines. That happens because the action description is made up of an `h2` (`Gigantic description ahead`), a `p` (`lorem ipsum...`) and another `p` (the jumbled mess).

All I could come up with was to just show the first child of the markdown viewer (the `h2` in this case) and restrict it to 3 lines, while hiding the other children. We might lose some content, but at least we shouldn't get that kind of mess

2022-05-02 21:30 UTC, lucca65 approved these changes
Nice, I'm ok with the solution of removing some of the content on the card, no problem

2022-05-04 12:48 UTC, juramos-2020 commented
OI @NeoVier 
segue feedback:

- Abra o modal para uma ação com uma descrição longa
- Verifique se você pode ler toda a descrição - **ok funcionando** 👍
- Verifique se os botões para reivindicar ou cancelar estão sempre visíveis na parte inferior do modal - **ok funcionando** 👍

- Se o conteúdo da ação for grande o suficiente, o modal agora poderá crescer mais alto (até 95% da altura da tela) - **ok funcionando** 👍

- ⚠**Apenas na versão mobile que precisa adicionar um espaçamento entre o "X de fechar" e o topo do modal.**⚠

2022-05-04 13:12 UTC, NeoVier commented
> Apenas na versão mobile que precisa adicionar um espaçamento entre o "X de fechar" e o topo do modal.

Só pra contextualizar, pelo que eu entendi, o espaçamento é essa barra branca:

![Untitled](https://user-images.githubusercontent.com/39280468/166687547-0773815d-8e57-43ca-bcf4-10ebdb3deb6e.png)

Qual seria o comportamento esperado?
1. Deixar o X "flutuando" em cima do conteúdo, o que cortaria uma parte do conteúdo
2. Não fazer com que o X fique sempre visível conforme o usuário faz o scroll do modal. Pode ser que prejudique um pouco a usabilidade do modal
3. Outra coisa?

Uma alternativa, ao invés de remover a barra branca, é adicionar um título (algo como "Reivindicar ação" ou "Reivindicando ação"), que vai ocupar esse espaço

2022-05-04 13:19 UTC, juramos-2020 commented
> ó pra contextualizar, pelo que eu entendi, o espaçamento é essa barra branca:
Isso, é o espaçamento entre um elemento e outro. Nesse caso entre o X e boda do modal.

![card de ações](https://user-images.githubusercontent.com/67649886/166689322-e74c4706-43fc-4e04-8a28-c33b19961f31.jpeg)

> Qual seria o comportamento esperado?
Ter uma borda branca igual tem na versão desktop

2022-05-04 19:42 UTC, merged