Enhancement/actions status
cambiatus/frontend pull request #787
Opened 2022-07-15 13:15 UTC by NeoVier

## What issue does this PR close
Closes #745 

## Changes Proposed ( a list of new changes introduced by this PR)
- Move `withPrivateKey` into Auth.elm, so it can be used on modules that can't import LoggedIn
- Use the same view function in the objectives page and the search results for actions

## How to test ( a list of instructions on how to test this PR)
- Search for actions, and make sure they look ok and work ok
- Go to the objectives page ("How to claim") and make sure the action cards look ok and work ok

2022-07-20 18:06 UTC, lucca65 requested changes
Na verdade, encontrei um problema estranho, que pode ser relacionado a essa PR. Na comunidade MIZU, no objetivo "Let's work together to improve our body, mind and spirit!". Esse objetivo não está completo. 

Temos a ação "resolver problema em prod" que tem uma imagem:
<img width="537" alt="Captura de Tela 2022-07-20 às 15 05 28" src="https://user-images.githubusercontent.com/1082127/180051813-3d3f5c6f-7b26-4dd3-828f-4b5825d4a051.png">

O problema é que essa ação não tem mais usos, mostra a mensagem que ela não deve ser reivindicada, mas o botão ainda tá disponível

2022-07-20 18:08 UTC, NeoVier commented
A solução seria não mostrar o botão de claim, certo?

2022-07-20 18:27 UTC, lucca65 commented
ou mostrá-lo desabilitado

2022-07-20 19:23 UTC, lucca65 requested changes
<img width="1339" alt="Captura de Tela 2022-07-20 às 16 22 27" src="https://user-images.githubusercontent.com/1082127/180064911-514af69f-9e68-460c-80dd-13053f65c081.png">


Alguns cards ficam justificados pra esquerda, outros ficam com 100%

2022-07-20 19:23 UTC, lucca65 commented
acabei de ver que tem um commit não buildado que parece que resolve justamente isso.... vou esperar compilar

2022-07-20 19:35 UTC, lucca65 approved these changes
✅

2022-07-22 12:23 UTC, juramos-2020 commented
Oi @NeoVier 

Ao clicar no "share", deveria abrir aquele modal de compartilhamento correto? Ele não está abrindo. O que está aparecendo é aquela barra de notificação de sucesso verde que diz " Copied to clipboard"

As ações concluída/completadas não estão aparecendo em "How to claim"

2022-07-22 12:29 UTC, juramos-2020 commented
A ação automática deve ter o ícone da ação na cor verde conforme design:
 https://www.figma.com/file/WbLY4a33elsepvpTYX6Mhn/Objetivos-%26-A%C3%A7%C3%B5es?node-id=1833%3A42839


O ícone só fica na cor cinza se a ação estiver fechada/ completa

2022-07-22 17:48 UTC, NeoVier commented
> Ao clicar no "share", deveria abrir aquele modal de compartilhamento correto? Ele não está abrindo. O que está aparecendo é aquela barra de notificação de sucesso verde que diz " Copied to clipboard"

@juramos-2020 isso muda de navegador pra navegador. Se o navegador suportar o menu, o menu abre. Caso contrário, o conteúdo é copiado para a área de transferência (pra ser colado com Ctrl+V)

---

> As ações concluída/completadas não estão aparecendo em "How to claim"

Nós queremos que elas apareçam nessa página? Acho que ali faz sentido só mostrar as ações abertas, e se o usuário quiser ver alguma que já foi fechada, ele pode achar pela busca

---

> O ícone só fica na cor cinza se a ação estiver fechada/ completa

Feito ✅

2022-07-22 17:58 UTC, lucca65 commented
> Nós queremos que elas apareçam nessa página? Acho que ali faz sentido só mostrar as ações abertas, e se o usuário quiser ver alguma que já foi fechada, ele pode achar pela busca

+1, não sei se faz tanto sentido, pois essa página iria ficar cheia de informação histórica, deixando a página longa. Talvez poderíamos ter um "..." pra mostrar essas fechadas pra quem quiser fazer uma consulta mais histórica. Nesse caso acho que podemos tratar em outra issue com o apoio do figma

2022-07-22 18:19 UTC, juramos-2020 commented
> isso muda de navegador pra navegador. Se o navegador suportar o menu, o menu abre. Caso contrário, o conteúdo é copiado para a área de transferência (pra ser colado com Ctrl+V)

Sucesso, testei em outro navegador e deu certo ☺️

> Nós queremos que elas apareçam nessa página? Acho que ali faz sentido só mostrar as ações abertas, e se o usuário quiser ver alguma que já foi fechada, ele pode achar pela busca

Sim faz sentido só mostrar as abertas. Essas ações concluídas não estão aparecendo na busca. 

Ex: eu tenho o objetivo "Teste de ações concluídas" e uma das ações concluídas se chama "ação com 2 reprovações". Quando eu coloco a palavra "ação" na busca, essa ação não aparece pra mim. Só aparece as ações ativas.

2022-07-22 19:18 UTC, NeoVier commented
A versão do backend de staging estava dessincronizada com esse PR 😅. As ações completas devem aparecer na busca agora

2022-07-22 19:30 UTC, juramos-2020 commented
Agora as ações estão aparecendo na busca @NeoVier . Tudo certo ☺️🤟

2022-07-22 19:32 UTC, juramos-2020 commented
e +1 sobre as ações concluídas não aparecerem em "How to earn" ☺️ Acho que nessa tela devemos focar nas ações para reivindicar ☺️

2022-07-22 19:41 UTC, merged